version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app

