# Generated by Django 4.2.13 on 2024-06-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativework',
            name='source_url',
        ),
        migrations.AddField(
            model_name='creativework',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creativework',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
