# Generated by Django 4.2.13 on 2024-06-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativework', '0002_remove_creativework_source_url_creativework_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
